//! `agencies` — legacy/mod.rs lines 14679–15616
use super::*;

pub fn now_datetime() -> (String, String) {
    let now = Local::now();
    let date = now.format("%Y-%m-%d").to_string();
    let time = now.format("%H:%M").to_string();
    (date, time)
}

pub fn normalize_agency_payment_status(status: &str) -> &'static str {
    if status.trim() == "غير واصل" {
        "غير واصل"
    } else {
        "واصل"
    }
}

pub fn agency_is_received(status: &str) -> bool {
    normalize_agency_payment_status(status) == "واصل"
}

pub fn is_borrower_account_kind(kind: &str) -> bool {
    matches!(kind.trim(), "زبون" | "وكالة")
}

fn fold_borrower_balance<P: rusqlite::Params>(
    db: &Connection,
    sql: &str,
    params: P,
) -> Result<Money, String> {
    let mut statement = db.prepare(sql).map_err(|error| error.to_string())?;
    let rows = statement
        .query_map(params, |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, Money>(1)?,
                row.get::<_, Option<String>>(2)?,
                row.get::<_, Option<String>>(3)?,
                row.get::<_, Option<String>>(4)?,
            ))
        })
        .map_err(|error| error.to_string())?;
    let mut balance = Money::zero();
    for row in rows {
        let (tx_type, amount, source_type, source_role, related_source_type) =
            row.map_err(|error| error.to_string())?;
        if tx_type.starts_with("تحويل") {
            continue;
        }
        if is_withdrawal_type(&tx_type) {
            balance += amount;
            continue;
        }
        let source_type = source_type.as_deref().unwrap_or("");
        let source_role = source_role.as_deref().unwrap_or("");
        let related_source_type = related_source_type.as_deref().unwrap_or("");
        let excluded_generated = matches!(
            source_type,
            "customer_installment_schedule" | "customer_sale_payment" | "customer_payment_reversal"
        ) || (source_type == "customer_payment"
            && source_role == "customer_payment"
            && related_source_type == "car")
            || related_source_type == "customer_payment_event";
        if (is_deposit_type(&tx_type) || tx_type.starts_with("واصل")) && !excluded_generated {
            balance -= amount;
        }
    }
    Ok(balance)
}

pub fn borrower_balance_for_currency(
    db: &Connection,
    partner_name: Option<&str>,
    kind: Option<&str>,
    currency: &str,
) -> Result<Money, String> {
    // Audit fix #21: paid types are matched by PREFIX (consistent with
    // Instructions.md §10.2 and the rest of the system), not by an exact-match
    // list, so any manual payment like "ايداع دفعة" correctly reduces the
    // customer balance. Rows generated by the installment schedule / sale down
    // payment / payment events stay excluded to prevent double counting.
    fold_borrower_balance(
        db,
        "SELECT type, amount, source_type, source_role, related_source_type
         FROM partner_transactions
         WHERE kind IN ('زبون', 'وكالة')
           AND (?1 IS NULL OR partner_name = ?1)
           AND (?2 IS NULL OR kind = ?2)
           AND COALESCE(currency, 'IQD') = ?3
           AND COALESCE(is_reversed, 0) = 0",
        params![partner_name, kind, currency],
    )
    .map_err(|e| format!("تعذر حساب رصيد الزبون/الوكالة: {e}"))
}

pub fn borrower_balance_for_account_currency(
    db: &Connection,
    account_id: i64,
    currency: &str,
) -> Result<Money, String> {
    fold_borrower_balance(
        db,
        "SELECT type, amount, source_type, source_role, related_source_type
         FROM partner_transactions
         WHERE account_id = ?1
           AND kind IN ('زبون', 'وكالة')
           AND COALESCE(currency, 'IQD') = ?2
           AND COALESCE(is_reversed, 0) = 0",
        params![account_id, currency],
    )
    .map_err(|e| format!("تعذر حساب رصيد الزبون/الوكالة: {e}"))
}

pub fn ensure_agency_account(
    db: &Connection,
    new_agent_name: &str,
    phone: &str,
) -> Result<i64, String> {
    let name = new_agent_name.trim();
    if name.is_empty() {
        return Err("اسم الوكيل الجديد مطلوب لإنشاء حساب الوكالة".to_string());
    }
    // §17.9: route through the normalized accounts table so the unique-name
    // constraint is enforced consistently across ALL account types.
    let phone_norm = normalize_phone_digits(phone);
    let normalized = normalize_account_name(name);
    validate_required_text(&normalized, "اسم حساب الوكالة")?;

    let existing: Option<(i64, String, String)> = db
        .query_row(
            "SELECT id, display_name, account_type FROM accounts WHERE normalized_name=?1",
            [&normalized],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
        )
        .optional()
        .map_err(|e| e.to_string())?;

    let account_id: i64 = if let Some((id, existing_display, existing_type)) = existing {
        if existing_type != "وكالة" {
            return Err(format!(
                "الاسم '{}' مستخدم مسبقًا لحساب من نوع '{}'",
                name, existing_type
            ));
        }
        if existing_display != name {
            return Err(format!(
                "الاسم '{}' يتعارض مع حساب موجود '{}'",
                name, existing_display
            ));
        }
        db.execute(
            "UPDATE accounts SET phone=CASE WHEN ?1<>'' THEN ?1 ELSE phone END,
             updated_at=strftime('%Y-%m-%d %H:%M:%S','now','localtime') WHERE id=?2",
            params![phone_norm.as_str(), id],
        )
        .map_err(|e| e.to_string())?;
        id
    } else {
        db.execute(
            "INSERT INTO accounts (display_name, normalized_name, account_type, phone)
             VALUES (?1, ?2, 'وكالة', ?3)",
            params![name, normalized, phone_norm.as_str()],
        )
        .map_err(|e| e.to_string())?;
        db.last_insert_rowid()
    };

    db.execute(
        "INSERT OR IGNORE INTO partners (partner_name, phone, total_amount, kind, account_id)
         VALUES (?1, ?2, '0', 'وكالة', ?3)",
        params![name, phone_norm.as_str(), account_id],
    )
    .map_err(|e| e.to_string())?;
    db.execute(
        "UPDATE partners SET account_id=?1,
         phone=CASE WHEN ?2<>'' THEN ?2 ELSE phone END
         WHERE account_id=?1",
        params![account_id, phone_norm.as_str()],
    )
    .map_err(|e| e.to_string())?;

    Ok(account_id)
}

pub fn agency_profit_note(old_agent_name: &str, new_agent_name: &str) -> String {
    format!(
        "ايداع ارباح وكالة {} {} رئيسي",
        old_agent_name.trim(),
        new_agent_name.trim()
    )
    .trim()
    .replace("  ", " ")
}

#[allow(clippy::too_many_arguments)]
pub fn insert_agency_customer_receivable(
    db: &Connection,
    agency_id: i64,
    new_agent_name: &str,
    phone: &str,
    car_number: &str,
    amount: Money,
    currency: &str,
    date: &str,
    time: &str,
    agency_notes: &str,
) -> Result<(), String> {
    if amount <= Money::zero() {
        return Ok(());
    }

    let customer_name = new_agent_name.trim();
    let account_id = ensure_agency_account(db, customer_name, phone)?;
    db.execute(
        "UPDATE agencies SET account_id=COALESCE(account_id,?1) WHERE id=?2",
        params![account_id, agency_id],
    )
    .map_err(|e| format!("تعذر ربط الوكالة بهوية الحساب: {e}"))?;
    db.execute(
        "UPDATE financial_ledger SET account_id_v2=?1
         WHERE reference_type='agency' AND reference_entity_id=?2
           AND account_type='receivable'",
        params![account_id, agency_id],
    )
    .map_err(|e| format!("تعذر ربط قيد الوكالة بهوية الحساب: {e}"))?;
    let operation_id: Option<String> = db
        .query_row(
            "SELECT operation_id FROM agencies WHERE id=?1",
            [agency_id],
            |row| row.get(0),
        )
        .map_err(|e| format!("تعذر قراءة هوية عملية الوكالة: {e}"))?;

    let note = if agency_notes.trim().is_empty() {
        format!(
            "غير واصل وكالة {} رقم السيارة {}",
            customer_name,
            car_number.trim()
        )
    } else {
        format!(
            "غير واصل وكالة {} رقم السيارة {} - {}",
            customer_name,
            car_number.trim(),
            agency_notes.trim()
        )
    }
    .trim()
    .replace("  ", " ");

    db.execute(
        "INSERT INTO partner_transactions (
            partner_name, kind, type, amount, date, time, notes, currency, payment_type,
            source_type, source_id, source_entity_id, source_role,
            affects_qasa, affects_partner_cash, affects_profit,
            related_source_type, related_source_id, related_entity_id,
            account_id, operation_id
         )
         VALUES (?1, 'وكالة', 'باقي وكالة', ?2, ?3, ?4, ?5, ?6, 'قاصه',
            'agency', CAST(?7 AS TEXT), ?7, 'agency_receivable', 0, 0, 0,
            'agency', CAST(?7 AS TEXT), ?7, ?8, ?9)",
        params![
            customer_name,
            amount,
            date.trim(),
            time.trim(),
            note,
            currency,
            agency_id,
            account_id,
            operation_id.as_deref(),
        ],
    )
    .map_err(|e| e.to_string())?;

    recalculate_partner_total(db, customer_name, "وكالة")
}

#[allow(clippy::too_many_arguments)]
pub fn distribute_agency_partner_effects(
    db: &Connection,
    amount: Money,
    currency: &str,
    date: &str,
    note: &str,
    source_type: &str,
    source_id: &str,
    received: bool,
) -> Result<(), String> {
    // ============================================================
    // FORENSIC FIX (re-audit 2026-07-10, Instructions.md §31.4):
    // Agency profit recognition now depends on payment_status.
    //
    //   - Cash agency (received=true): profit_recognition + cash_movement
    //     are both created. Profit enters the Profit card, Qasa, and Cash.
    //
    //   - Credit agency (received=false): NO profit_recognition and NO
    //     cash_movement. Only a receivable row tracks the amount owed.
    //     Profit is deferred until the agency is marked "واصل" via
    //     set_agency_receivable_status, at which point both rows are
    //     created retroactively.
    //
    // This REPLACES the old §30.9 behavior which recognized profit
    // immediately regardless of payment status. The new rule is stricter:
    // no profit enters the system until real cash is received.
    // ============================================================
    if received {
        // Profit recognition (affects_profit=1, does NOT enter Qasa/Cash).
        distribute_to_partners_50_with_effects(
            db,
            amount,
            currency,
            date,
            "قاصه",
            "ايداع ارباح وكالة",
            note,
            source_type,
            source_id,
            "profit_recognition",
            false,
            false,
            true,
        )?;

        // Cash movement (affects_qasa=1, affects_partner_cash=1, NOT profit).
        distribute_to_partners_50_with_effects(
            db,
            amount,
            currency,
            date,
            "قاصه",
            "ايداع ارباح وكالة",
            note,
            source_type,
            source_id,
            "cash_movement",
            true,
            true,
            false,
        )?;
    }
    // If !received: NO profit_recognition, NO cash_movement.
    // The receivable row is created separately by the caller
    // (insert_agency_customer_receivable) and tracks the amount owed.
    Ok(())
}

pub fn distribute_agency_withdrawal_partner_effects(
    db: &Connection,
    amount: Money,
    currency: &str,
    date: &str,
    note: &str,
    source_type: &str,
    source_id: &str,
) -> Result<(), String> {
    if amount <= Money::zero() {
        return Ok(());
    }

    deduct_from_partners_5050_with_effects(
        db,
        amount,
        currency,
        date,
        "قاصه",
        "سحب ارباح وكالة",
        note,
        source_type,
        source_id,
        "cash_movement",
        true,
        true,
        false,
    )?;

    distribute_signed_profit_recognition_50_with_related(
        db,
        -amount,
        currency,
        date,
        "قاصه",
        "سحب ارباح وكالة",
        note,
        source_type,
        source_id,
        None,
        None,
    )
}

#[allow(clippy::type_complexity)]
pub fn rebuild_agency_partner_entries(db: &Connection, agency_id: i64) -> Result<(), String> {
    let agency_info: Result<
        (
            String,
            String,
            String,
            String,
            Money,
            Money,
            String,
            String,
            String,
            String,
        ),
        rusqlite::Error,
    > = db.query_row(
        "SELECT old_agent_name, new_agent_name, phone, car_number, amount_usd, amount_iqd,
                date, time, notes, COALESCE(payment_status, 'واصل')
         FROM agencies WHERE id = ?1",
        [agency_id],
        |row| {
            Ok((
                row.get(0)?,
                row.get(1)?,
                row.get(2)?,
                row.get(3)?,
                row.get(4)?,
                row.get(5)?,
                row.get(6)?,
                row.get(7)?,
                row.get(8)?,
                row.get(9)?,
            ))
        },
    );

    let (
        old_agent_name,
        new_agent_name,
        phone,
        car_number,
        amount_usd,
        amount_iqd,
        date,
        time,
        notes,
        payment_status,
    ) = match agency_info {
        Ok(info) => info,
        Err(rusqlite::Error::QueryReturnedNoRows) => return Ok(()),
        Err(e) => return Err(e.to_string()),
    };
    let received = agency_is_received(&payment_status);

    // Delete ALL old partner rows for this agency
    // Handles legacy cash_movement, profit_recognition, receivable, and current agency_profit rows
    delete_partner_transactions_by_source_with_ledger(db, "agency", &agency_id.to_string(), None)?;

    let note = agency_profit_note(&old_agent_name, &new_agent_name);

    if amount_usd > Money::zero() {
        distribute_agency_partner_effects(
            db,
            amount_usd,
            "USD",
            &date,
            &note,
            "agency",
            &agency_id.to_string(),
            received,
        )?;
        if !received {
            insert_agency_customer_receivable(
                db,
                agency_id,
                &new_agent_name,
                &phone,
                &car_number,
                amount_usd,
                "USD",
                &date,
                &time,
                &notes,
            )?;
        }
    }

    if amount_iqd > Money::zero() {
        distribute_agency_partner_effects(
            db,
            amount_iqd,
            "IQD",
            &date,
            &note,
            "agency",
            &agency_id.to_string(),
            received,
        )?;
        if !received {
            insert_agency_customer_receivable(
                db,
                agency_id,
                &new_agent_name,
                &phone,
                &car_number,
                amount_iqd,
                "IQD",
                &date,
                &time,
                &notes,
            )?;
        }
    }

    Ok(())
}

#[allow(clippy::type_complexity)]
pub fn rebuild_agency_transaction_partner_entries(
    db: &Connection,
    tx_id: i64,
) -> Result<(), String> {
    delete_partner_transactions_by_source_with_ledger(
        db,
        "agency_transaction",
        &tx_id.to_string(),
        None,
    )?;

    let tx_info: Result<
        (i64, String, Money, String, String, String, String, String),
        rusqlite::Error,
    > = db.query_row(
        "SELECT at.agency_id, at.type_, at.amount, COALESCE(at.currency, 'IQD'),
                    at.date, a.old_agent_name, a.new_agent_name,
                    COALESCE(a.payment_status, 'واصل')
             FROM agency_transactions at
             JOIN agencies a ON a.id = at.agency_id
             WHERE at.id = ?1",
        [tx_id],
        |row| {
            Ok((
                row.get(0)?,
                row.get(1)?,
                row.get(2)?,
                row.get(3)?,
                row.get(4)?,
                row.get(5)?,
                row.get(6)?,
                row.get(7)?,
            ))
        },
    );
    let (
        _agency_id,
        tx_type,
        amount,
        currency,
        date,
        old_agent_name,
        new_agent_name,
        payment_status,
    ) = match tx_info {
        Ok(info) => info,
        Err(rusqlite::Error::QueryReturnedNoRows) => return Ok(()),
        Err(e) => return Err(e.to_string()),
    };

    let note = format!(
        "{} ارباح وكالة {} {}",
        tx_type.trim(),
        old_agent_name.trim(),
        new_agent_name.trim()
    )
    .trim()
    .replace("  ", " ");

    // FORENSIC FIX (re-audit 2026-07-11, FORENSIC-RUST-1-1):
    // Per Instructions.md §31.4.5, agency_transactions follow the same
    // cash-vs-credit rule as their parent agency. If the parent agency's
    // payment_status is "غير واصل" (credit), the transaction amount must
    // NOT be recognized as profit + cash immediately. Instead, it should
    // be added to the receivable. Only when the agency is marked "واصل"
    // should the profit + cash be recognized.
    //
    // Previously, `received=true` was hardcoded for deposits, violating
    // §31.4.4/§31.4.5 for credit agencies.
    let received = payment_status.trim() == "واصل";

    if tx_type.trim() == "ايداع" {
        distribute_agency_partner_effects(
            db,
            amount,
            &currency,
            &date,
            &note,
            "agency_transaction",
            &tx_id.to_string(),
            received,
        )?;
    } else {
        distribute_agency_withdrawal_partner_effects(
            db,
            amount,
            &currency,
            &date,
            &note,
            "agency_transaction",
            &tx_id.to_string(),
        )?;
    }

    Ok(())
}

pub fn rebuild_all_agency_partner_entries(db: &Connection) -> Result<(), String> {
    let mut agency_stmt = db
        .prepare("SELECT id FROM agencies")
        .map_err(|e| e.to_string())?;
    let agency_ids = agency_stmt
        .query_map([], |row| row.get::<_, i64>(0))
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;
    drop(agency_stmt);
    for agency_id in agency_ids {
        rebuild_agency_partner_entries(db, agency_id)?;
    }

    let mut tx_stmt = db
        .prepare("SELECT id FROM agency_transactions")
        .map_err(|e| e.to_string())?;
    let tx_ids = tx_stmt
        .query_map([], |row| row.get::<_, i64>(0))
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;
    drop(tx_stmt);
    for tx_id in tx_ids {
        rebuild_agency_transaction_partner_entries(db, tx_id)?;
    }

    Ok(())
}

#[tauri::command]
pub fn get_agencies(state: State<AppState>) -> Result<Vec<Agency>, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let mut stmt = db
        .prepare(
            "SELECT id, old_agent_name, car_type, car_number, car_model, color, new_agent_name, phone,
                    amount_usd, amount_iqd, notes, COALESCE(payment_status, 'واصل'), date, time, version
             FROM agencies WHERE COALESCE(payment_status,'واصل')<>'محذوفة' ORDER BY id ASC",
        )
        .map_err(|e| e.to_string())?;

    let agencies = stmt
        .query_map([], |row| {
            Ok(Agency {
                id: row.get(0)?,
                old_agent_name: row.get(1)?,
                car_type: row.get(2)?,
                car_number: row.get(3)?,
                car_model: row.get(4)?,
                color: row.get(5)?,
                new_agent_name: row.get(6)?,
                phone: row.get(7)?,
                amount_usd: row.get(8)?,
                amount_iqd: row.get(9)?,
                notes: row.get(10)?,
                payment_status: row.get(11)?,
                date: row.get(12)?,
                time: row.get(13)?,
                version: row.get(14)?,
            })
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;

    Ok(agencies)
}

#[allow(clippy::too_many_arguments)]
#[tauri::command]
pub fn add_agency(
    state: State<AppState>,
    old_agent_name: String,
    car_type: String,
    car_number: String,
    car_model: String,
    color: String,
    new_agent_name: String,
    phone: String,
    amount_usd: Money,
    amount_iqd: Money,
    notes: String,
    payment_status: Option<String>,
    creation_token: Option<String>,
    session_token: String,
) -> Result<i64, String> {
    // Audit fix #13: validate agency amounts before any write.
    validate_required_text(&old_agent_name, "اسم الوكيل القديم")?;
    validate_required_text(&new_agent_name, "اسم الوكيل الجديد")?;
    validate_non_negative_amount(amount_usd, "مبلغ الدولار")?;
    validate_non_negative_amount(amount_iqd, "مبلغ الدينار")?;
    if amount_usd <= Money::zero() && amount_iqd <= Money::zero() {
        return Err("يجب إدخال مبلغ وكالة أكبر من صفر بالدينار أو الدولار".to_string());
    }

    let mut db_guard = state.db.lock().map_err(|e| e.to_string())?;
    let (db, actor_user_id) = begin_admin_transaction(&mut db_guard, &session_token)?;
    let (operation_date, _) = now_datetime();
    ensure_accounting_period_open(&db, &operation_date)?;
    let creation_token = creation_token
        .map(|token| token.trim().to_string())
        .filter(|token| !token.is_empty());
    let payment_status =
        normalize_agency_payment_status(payment_status.as_deref().unwrap_or("واصل"));

    let idempotency_payload = serde_json::json!({
        "old_agent_name": old_agent_name,
        "car_type": car_type,
        "car_number": car_number,
        "car_model": car_model,
        "color": color,
        "new_agent_name": new_agent_name,
        "phone": phone,
        "amount_usd": amount_usd,
        "amount_iqd": amount_iqd,
        "notes": notes,
        "payment_status": payment_status,
    });
    if let IdempotencyClaim::Replay(reference) = claim_idempotent_creation(
        &db,
        creation_token.as_deref(),
        "add_agency",
        &idempotency_payload,
    )? {
        return reference
            .parse::<i64>()
            .map_err(|_| "معرّف نتيجة طلب الوكالة السابق غير صالح".to_string());
    }

    // Double-click/retry protection independent of the frontend token. The
    // operation timestamp has sub-second precision, unlike agencies.time which
    // stores minutes only. Matching the full payload avoids suppressing a
    // different legitimate agency created immediately afterwards.
    let recent_dup_id: Option<i64> = db
        .query_row(
            "SELECT a.id
             FROM agencies a
             JOIN operations o ON o.id=a.operation_id
             WHERE a.old_agent_name=?1 AND a.new_agent_name=?2
               AND a.car_type=?3 AND a.car_number=?4 AND a.car_model=?5
               AND a.color=?6 AND a.phone=?7
               AND a.amount_iqd=?8 AND a.amount_usd=?9
               AND COALESCE(a.notes,'')=?10 AND a.payment_status=?11
               AND (julianday('now')-julianday(o.created_at))*86400.0 < 5.0
             ORDER BY a.id DESC LIMIT 1",
            params![
                old_agent_name.trim(),
                new_agent_name.trim(),
                car_type.trim(),
                car_number.trim(),
                car_model.trim(),
                color.trim(),
                phone.trim(),
                amount_iqd,
                amount_usd,
                notes.trim(),
                payment_status,
            ],
            |row| row.get(0),
        )
        .optional()
        .map_err(|e| e.to_string())?;
    if let Some(existing_id) = recent_dup_id {
        return Ok(existing_id);
    }

    let (date, time): (String, String) = db
        .query_row(
            "SELECT strftime('%Y-%m-%d', 'now', 'localtime'), strftime('%H:%M', 'now', 'localtime')",
            [],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .map_err(|e| format!("تعذر تحديد وقت الوكالة: {e}"))?;

    let account_id = ensure_partner_exists(&db, &old_agent_name, &phone, "وكالة")?;
    let operation_id = new_ledger_token("agency_creation");
    db.execute(
        "INSERT INTO operations
         (id,operation_type,status,creation_token,actor_user_id,created_at)
         VALUES (?1,'agency_creation','active',?2,?3,
                 strftime('%Y-%m-%dT%H:%M:%fZ','now'))",
        params![operation_id, creation_token.as_deref(), actor_user_id],
    )
    .map_err(|e| format!("تعذر إنشاء هوية عملية الوكالة: {e}"))?;

    db.execute(
        "INSERT INTO agencies (old_agent_name, car_type, car_number, car_model, color,
             new_agent_name, phone, amount_usd, amount_iqd, notes, payment_status, date,
             time, creation_token, operation_id, account_id)
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16)",
        params![
            old_agent_name.trim(),
            car_type.trim(),
            car_number.trim(),
            car_model.trim(),
            color.trim(),
            new_agent_name.trim(),
            phone.trim(),
            amount_usd,
            amount_iqd,
            notes.trim(),
            payment_status,
            date.clone(),
            time,
            creation_token.as_deref(),
            operation_id,
            account_id,
        ],
    )
    .map_err(|e| e.to_string())?;

    let new_id = db.last_insert_rowid();

    // Record setup entries in ledger
    record_agency_ledger_entries(&db, new_id)?;
    rebuild_agency_partner_entries(&db, new_id)?;
    db.execute(
        "UPDATE partner_transactions SET operation_id=?1
         WHERE source_type='agency' AND source_entity_id=?2",
        params![operation_id, new_id],
    )
    .map_err(|e| format!("تعذر ربط حركات الوكالة بالعملية: {e}"))?;
    db.execute(
        "UPDATE financial_ledger SET operation_id=?1
         WHERE (reference_type='agency' AND reference_entity_id=?2)
            OR (reference_type='partner_transaction' AND reference_entity_id IN (
                SELECT id FROM partner_transactions
                WHERE source_type='agency' AND source_entity_id=?2))",
        params![operation_id, new_id],
    )
    .map_err(|e| format!("تعذر ربط قيود الوكالة بالعملية: {e}"))?;
    append_audit_event_with_details(
        &db,
        actor_user_id,
        "agency",
        Some(new_id),
        "create_agency",
        Some(&session_token),
        creation_token.as_deref(),
        AuditEventDetails {
            operation_id: Some(&operation_id),
            account_id: Some(account_id),
            ..Default::default()
        },
    )?;
    complete_idempotent_creation(&db, creation_token.as_deref(), &new_id.to_string())?;

    db.commit().map_err(|e| e.to_string())?;

    Ok(new_id)
}

#[allow(clippy::too_many_arguments)]
#[tauri::command]
pub fn update_agency(
    state: State<AppState>,
    id: i64,
    old_agent_name: String,
    car_type: String,
    car_number: String,
    car_model: String,
    color: String,
    new_agent_name: String,
    phone: String,
    amount_usd: Money,
    amount_iqd: Money,
    notes: String,
    payment_status: Option<String>,
    expected_version: i64,
    session_token: String,
) -> Result<(), String> {
    // Audit fix #13: validate agency amounts before any write.
    validate_required_text(&old_agent_name, "اسم الوكيل القديم")?;
    validate_required_text(&new_agent_name, "اسم الوكيل الجديد")?;
    validate_non_negative_amount(amount_usd, "مبلغ الدولار")?;
    validate_non_negative_amount(amount_iqd, "مبلغ الدينار")?;
    if amount_usd <= Money::zero() && amount_iqd <= Money::zero() {
        return Err("يجب إدخال مبلغ وكالة أكبر من صفر بالدينار أو الدولار".to_string());
    }

    let mut db_guard = state.db.lock().map_err(|e| e.to_string())?;
    let (db, actor_user_id) = begin_admin_transaction(&mut db_guard, &session_token)?;
    let (agency_date, current_version): (String, i64) = db
        .query_row(
            "SELECT date,version FROM agencies WHERE id=?1",
            [id],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .map_err(|_| "الوكالة المطلوبة غير موجودة".to_string())?;
    if current_version != expected_version {
        return Err(format!(
            "تعارض تعديل الوكالة: النسخة الحالية {current_version} وليست {expected_version}"
        ));
    }
    ensure_accounting_period_open(&db, &agency_date)?;

    // Phase 14: Delete all partner rows by agency_id (cash_movement + profit_recognition)
    delete_partner_transactions_by_source_with_ledger(&db, "agency", &id.to_string(), None)?;

    // تحديث جدول الوكالات بالبيانات الجديدة
    let payment_status =
        normalize_agency_payment_status(payment_status.as_deref().unwrap_or("واصل"));
    let changed = db
        .execute(
            "UPDATE agencies SET old_agent_name = ?1, car_type = ?2, car_number = ?3,
         car_model = ?4, color = ?5, new_agent_name = ?6, phone = ?7,
         amount_usd = ?8, amount_iqd = ?9, notes = ?10, payment_status = ?11,
         version=version+1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
         WHERE id = ?12 AND version=?13",
            (
                old_agent_name.trim(),
                car_type.trim(),
                car_number.trim(),
                car_model.trim(),
                color.trim(),
                new_agent_name.trim(),
                phone.trim(),
                amount_usd,
                amount_iqd,
                notes.trim(),
                payment_status,
                id,
                expected_version,
            ),
        )
        .map_err(|e| e.to_string())?;
    if changed != 1 {
        return Err("تعارض تعديل الوكالة أثناء الحفظ".to_string());
    }

    // Record setup entries in ledger
    record_agency_ledger_entries(&db, id)?;
    rebuild_agency_partner_entries(&db, id)?;
    append_audit_event(
        &db,
        actor_user_id,
        "agency",
        Some(id),
        "update_agency",
        Some(&session_token),
        None,
    )?;

    db.commit().map_err(|e| e.to_string())?;

    Ok(())
}

#[tauri::command]
pub fn delete_agency(
    state: State<AppState>,
    id: i64,
    expected_version: i64,
    session_token: String,
) -> Result<(), String> {
    let mut db_guard = state.db.lock().map_err(|e| e.to_string())?;
    let (db, actor_user_id) = begin_admin_transaction(&mut db_guard, &session_token)?;
    let (current_version, operation_id, account_id, payment_status): (i64, String, i64, String) =
        db.query_row(
            "SELECT version,operation_id,account_id,payment_status FROM agencies WHERE id=?1",
            [id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?)),
        )
        .map_err(|_| "الوكالة المطلوبة غير موجودة أو تفتقد الهوية الرقمية".to_string())?;
    if current_version != expected_version {
        return Err(format!(
            "تعارض تعديل الوكالة: النسخة الحالية {} وليست {}",
            current_version, expected_version
        ));
    }
    if payment_status == "محذوفة" {
        return Err("الوكالة ملغاة مسبقًا".to_string());
    }
    let (reversal_date, _) = now_datetime();
    ensure_accounting_period_open(&db, &reversal_date)?;
    let cancellation_operation_id = new_ledger_token("agency_cancellation");
    db.execute(
        "INSERT INTO operations
         (id,operation_type,status,reverses_operation_id,actor_user_id,created_at)
         VALUES (?1,'agency_cancellation','active',?2,?3,
                 strftime('%Y-%m-%dT%H:%M:%fZ','now'))",
        params![cancellation_operation_id, operation_id, actor_user_id],
    )
    .map_err(|e| format!("تعذر إنشاء عملية إلغاء الوكالة: {e}"))?;

    let sources: Vec<(String, String, String)> = {
        let mut stmt = db
            .prepare(
                "SELECT DISTINCT source_type,source_id,source_role
                 FROM partner_transactions
                 WHERE operation_id=?1 OR operation_id IN (
                     SELECT operation_id FROM agency_transactions WHERE agency_id=?2)",
            )
            .map_err(|e| e.to_string())?;
        let rows = stmt
            .query_map(params![operation_id, id], |row| {
                Ok((row.get(0)?, row.get(1)?, row.get(2)?))
            })
            .map_err(|e| e.to_string())?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())?;
        rows
    };
    for (source_type, source_id, source_role) in sources {
        append_partner_transaction_reversals_by_source(
            &db,
            &source_type,
            &source_id,
            &source_role,
            &cancellation_operation_id,
        )?;
    }
    reverse_ledger_entries(&db, "agency", &id.to_string())?;
    let tx_ids: Vec<i64> = {
        let mut stmt = db
            .prepare("SELECT id FROM agency_transactions WHERE agency_id=?1")
            .map_err(|e| e.to_string())?;
        let rows = stmt
            .query_map([id], |row| row.get(0))
            .map_err(|e| e.to_string())?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())?;
        rows
    };
    for tx_id in tx_ids {
        reverse_ledger_entries(&db, "agency_transaction", &tx_id.to_string())?;
    }
    db.execute(
        "UPDATE financial_ledger SET operation_id=?1
         WHERE reverses_ledger_id IN (
             SELECT original.id FROM financial_ledger original
             WHERE original.operation_id=?2 OR original.operation_id IN (
                 SELECT operation_id FROM agency_transactions WHERE agency_id=?3))",
        params![cancellation_operation_id, operation_id, id],
    )
    .map_err(|e| format!("تعذر ربط قيود عكس الوكالة: {e}"))?;
    db.execute(
        "UPDATE operations
         SET status='reversed',reversed_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),
             reversal_operation_id=?1
         WHERE status='active' AND (id=?2 OR id IN (
             SELECT operation_id FROM agency_transactions WHERE agency_id=?3))",
        params![cancellation_operation_id, operation_id, id],
    )
    .map_err(|e| format!("تعذر عكس عمليات الوكالة: {e}"))?;
    let changed = db
        .execute(
            "UPDATE agencies SET payment_status='محذوفة',version=version+1,
             updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
             WHERE id=?1 AND version=?2",
            params![id, expected_version],
        )
        .map_err(|e| format!("تعذر إلغاء الوكالة: {e}"))?;
    if changed != 1 {
        return Err("تعارض تعديل الوكالة أثناء الإلغاء".to_string());
    }
    append_audit_event_with_details(
        &db,
        actor_user_id,
        "agency",
        Some(id),
        "cancel_agency",
        Some(&session_token),
        None,
        AuditEventDetails {
            operation_id: Some(&cancellation_operation_id),
            account_id: Some(account_id),
            reason: Some("إلغاء الوكالة مع حفظ التاريخ المالي"),
            ..Default::default()
        },
    )?;
    recalculate_all_partners(&db)?;
    db.commit().map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub fn get_agency_transactions(
    state: State<AppState>,
    agency_id: i64,
) -> Result<Vec<AgencyTransaction>, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    let mut stmt = db
        .prepare(
            "SELECT id,agency_id,date,time,type_,amount,currency,notes,
                    version,operation_id,status
             FROM agency_transactions
             WHERE agency_id=?1 AND status='active' ORDER BY id ASC",
        )
        .map_err(|e| e.to_string())?;

    let transactions = stmt
        .query_map([agency_id], |row| {
            Ok(AgencyTransaction {
                id: row.get(0)?,
                agency_id: row.get(1)?,
                date: row.get(2)?,
                time: row.get(3)?,
                type_: row.get(4)?,
                amount: row.get(5)?,
                currency: row.get(6)?,
                notes: row.get(7)?,
                version: row.get(8)?,
                operation_id: row.get(9)?,
                status: row.get(10)?,
            })
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;

    Ok(transactions)
}

#[allow(clippy::too_many_arguments)]
#[tauri::command]
pub fn add_agency_transaction(
    state: State<AppState>,
    agency_id: i64,
    type_: String,
    amount: Money,
    date: String,
    notes: Option<String>,
    currency: Option<String>,
    creation_token: Option<String>,
    session_token: String,
) -> Result<(), String> {
    // Audit fix #13: validate agency transaction inputs before any write.
    validate_required_text(&type_, "نوع الحركة")?;
    validate_positive_amount(amount, "المبلغ")?;
    validate_required_text(&date, "التاريخ")?;
    if let Some(ref curr) = currency {
        validate_currency(curr)?;
    }

    let mut db_guard = state.db.lock().map_err(|e| e.to_string())?;
    let (db, actor_user_id) = begin_admin_transaction(&mut db_guard, &session_token)?;
    ensure_accounting_period_open(&db, &date)?;

    // FORENSIC FIX (re-audit 2026-07-11, FORENSIC-RUST-1-2):
    // Idempotency: if a creation_token is provided and an agency_transaction
    // with that token already exists, return success without creating a duplicate.
    let creation_token = creation_token
        .map(|t| t.trim().to_string())
        .filter(|t| !t.is_empty());
    let idempotency_payload = serde_json::json!({
        "agency_id": agency_id,
        "type": type_,
        "amount": amount,
        "date": date,
        "notes": notes,
        "currency": currency,
    });
    if let IdempotencyClaim::Replay(_) = claim_idempotent_creation(
        &db,
        creation_token.as_deref(),
        "add_agency_transaction",
        &idempotency_payload,
    )? {
        return Ok(());
    }

    let time: String = db
        .query_row("SELECT strftime('%H:%M', 'now', 'localtime')", [], |row| {
            row.get(0)
        })
        .map_err(|e| format!("تعذر تحديد وقت حركة الوكالة: {e}"))?;

    let account_id: i64 = db
        .query_row(
            "SELECT account_id FROM agencies WHERE id=?1",
            [agency_id],
            |row| row.get(0),
        )
        .map_err(|_| "الوكالة المطلوبة لا تملك حسابًا رقميًا صالحًا".to_string())?;
    let operation_id = new_ledger_token("agency_transaction_creation");
    db.execute(
        "INSERT INTO operations
         (id,operation_type,status,creation_token,actor_user_id,created_at)
         VALUES (?1,'agency_transaction_creation','active',?2,?3,
                 strftime('%Y-%m-%dT%H:%M:%fZ','now'))",
        params![operation_id, creation_token.as_deref(), actor_user_id],
    )
    .map_err(|e| format!("تعذر إنشاء هوية عملية حركة الوكالة: {e}"))?;

    db.execute(
        "INSERT INTO agency_transactions
         (agency_id,date,time,type_,amount,currency,notes,creation_token,operation_id)
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9)",
        params![
            agency_id,
            date.trim(),
            time,
            type_.trim(),
            amount,
            currency.as_deref(),
            notes.as_deref(),
            creation_token.as_deref(),
            operation_id,
        ],
    )
    .map_err(|e| e.to_string())?;

    let tx_id = db.last_insert_rowid();

    // Record ledger entry
    record_agency_transaction_ledger_entries(&db, tx_id)?;

    rebuild_agency_transaction_partner_entries(&db, tx_id)?;

    db.execute(
        "UPDATE partner_transactions SET operation_id=?1
         WHERE source_type='agency_transaction' AND source_entity_id=?2",
        params![operation_id, tx_id],
    )
    .map_err(|e| format!("تعذر ربط حركات الشركاء بحركة الوكالة: {e}"))?;
    db.execute(
        "UPDATE financial_ledger SET operation_id=?1
         WHERE (reference_type='agency_transaction' AND reference_entity_id=?2)
            OR (reference_type='partner_transaction' AND reference_entity_id IN (
                SELECT id FROM partner_transactions
                WHERE source_type='agency_transaction' AND source_entity_id=?2))",
        params![operation_id, tx_id],
    )
    .map_err(|e| format!("تعذر ربط قيود حركة الوكالة بالعملية: {e}"))?;
    append_audit_event_with_details(
        &db,
        actor_user_id,
        "agency_transaction",
        Some(tx_id),
        "create_agency_transaction",
        Some(&session_token),
        creation_token.as_deref(),
        AuditEventDetails {
            operation_id: Some(&operation_id),
            account_id: Some(account_id),
            ..Default::default()
        },
    )?;
    complete_idempotent_creation(&db, creation_token.as_deref(), &tx_id.to_string())?;

    db.commit().map_err(|e| e.to_string())?;

    Ok(())
}

#[tauri::command]
pub fn delete_agency_transaction(
    state: State<AppState>,
    id: i64,
    expected_version: i64,
    session_token: String,
) -> Result<(), String> {
    let mut db_guard = state.db.lock().map_err(|e| e.to_string())?;
    let (db, actor_user_id) = begin_admin_transaction(&mut db_guard, &session_token)?;
    type AgencyTransactionIdentity = (
        i64,
        String,
        i64,
        String,
        Money,
        Option<String>,
        String,
        String,
        i64,
    );
    let (agency_id, operation_id, version, date, amount, currency, type_, status, account_id):
        AgencyTransactionIdentity = db
        .query_row(
            "SELECT at.agency_id,at.operation_id,at.version,at.date,at.amount,
                    at.currency,at.type_,at.status,a.account_id
             FROM agency_transactions at
             JOIN agencies a ON a.id=at.agency_id
             WHERE at.id=?1",
            [id],
            |row| {
                Ok((
                    row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?, row.get(4)?,
                    row.get(5)?, row.get(6)?, row.get(7)?, row.get(8)?,
                ))
            },
        )
        .map_err(|_| "حركة الوكالة المطلوبة غير موجودة أو تفتقد الهوية الرقمية".to_string())?;
    if status != "active" {
        return Err("حركة الوكالة ملغاة أو معكوسة مسبقًا".to_string());
    }
    if version != expected_version {
        return Err(format!(
            "تعارض تعديل حركة الوكالة: النسخة الحالية {version} وليست {expected_version}"
        ));
    }
    let (reversal_date, reversal_time) = now_datetime();
    ensure_accounting_period_open(&db, &reversal_date)?;

    let reversal_operation_id = new_ledger_token("agency_transaction_reversal");
    db.execute(
        "INSERT INTO operations
         (id,operation_type,status,reverses_operation_id,actor_user_id,created_at)
         VALUES (?1,'agency_transaction_reversal','active',?2,?3,
                 strftime('%Y-%m-%dT%H:%M:%fZ','now'))",
        params![reversal_operation_id, operation_id, actor_user_id],
    )
    .map_err(|e| format!("تعذر إنشاء عملية عكس حركة الوكالة: {e}"))?;
    db.execute(
        "INSERT INTO agency_transactions
         (agency_id,date,time,type_,amount,currency,notes,operation_id,version,
          updated_at,status,reversed_at,reverses_agency_transaction_id)
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8,1,
                 strftime('%Y-%m-%dT%H:%M:%fZ','now'),'reversal',
                 strftime('%Y-%m-%dT%H:%M:%fZ','now'),?9)",
        params![
            agency_id,
            reversal_date,
            reversal_time,
            format!("عكس: {type_}"),
            -amount,
            currency,
            format!("عكس حركة الوكالة رقم {id} بتاريخ {date}"),
            reversal_operation_id,
            id,
        ],
    )
    .map_err(|e| format!("تعذر إضافة صف عكس حركة الوكالة: {e}"))?;

    let source_roles: Vec<String> = {
        let mut stmt = db
            .prepare(
                "SELECT DISTINCT source_role FROM partner_transactions
                 WHERE source_type='agency_transaction' AND source_entity_id=?1
                   AND source_role IS NOT NULL AND COALESCE(is_reversed,0)=0",
            )
            .map_err(|e| e.to_string())?;
        let rows = stmt
            .query_map([id], |row| row.get(0))
            .map_err(|e| e.to_string())?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())?;
        rows
    };
    for source_role in source_roles {
        append_partner_transaction_reversals_by_source(
            &db,
            "agency_transaction",
            &id.to_string(),
            &source_role,
            &reversal_operation_id,
        )?;
    }
    reverse_ledger_entries(&db, "agency_transaction", &id.to_string())?;
    db.execute(
        "UPDATE financial_ledger SET operation_id=?1
         WHERE reverses_ledger_id IN (
             SELECT original.id FROM financial_ledger original WHERE original.operation_id=?2
         )",
        params![reversal_operation_id, operation_id],
    )
    .map_err(|e| format!("تعذر ربط قيود عكس حركة الوكالة: {e}"))?;
    db.execute(
        "UPDATE operations
         SET status='reversed',reversed_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),
             reversal_operation_id=?1
         WHERE id=?2 AND status='active'",
        params![reversal_operation_id, operation_id],
    )
    .map_err(|e| format!("تعذر عكس عملية حركة الوكالة: {e}"))?;
    let changed = db
        .execute(
            "UPDATE agency_transactions
             SET status='reversed',version=version+1,
                 updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),
                 reversed_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),
                 reversal_operation_id=?1
             WHERE id=?2 AND version=?3 AND status='active'",
            params![reversal_operation_id, id, expected_version],
        )
        .map_err(|e| format!("تعذر عكس حركة الوكالة: {e}"))?;
    if changed != 1 {
        return Err("تعارض تعديل حركة الوكالة أثناء العكس".to_string());
    }
    append_audit_event_with_details(
        &db,
        actor_user_id,
        "agency_transaction",
        Some(id),
        "reverse_agency_transaction",
        Some(&session_token),
        None,
        AuditEventDetails {
            operation_id: Some(&reversal_operation_id),
            account_id: Some(account_id),
            version: Some(version + 1),
            reason: Some("عكس حركة الوكالة"),
            ..Default::default()
        },
    )?;
    recalculate_all_partners(&db)?;
    db.commit().map_err(|e| e.to_string())?;
    Ok(())
}
