import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    fontFamily: "Tajawal",
    paddingTop: 16,
    paddingBottom: 48,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: "#ffffff",
    borderWidth: 0.8,
    borderStyle: "solid",
    borderColor: "#d6b46a",
  },

  header: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "#cbd5e1",
    paddingBottom: 6,
    marginBottom: 7,
  },
  headerRight: { flex: 1, alignItems: "flex-end" },
  headerCenter: { width: 92, alignItems: "center" },
  headerLeft: { flex: 1, alignItems: "flex-start" },
  logo: { width: 92, height: 78, objectFit: "contain" },
  companyNameAr: { fontSize: 15, fontWeight: 900, color: "#111827", textAlign: "right" },
  companySubAr: { fontSize: 10.5, fontWeight: 700, color: "#57534e", textAlign: "right" },
  companyCity: { fontSize: 9, fontWeight: 500, color: "#78716c", textAlign: "right" },
  companyNameEn: { fontSize: 15, fontWeight: 900, color: "#111827", textAlign: "left" },
  companySubEn: { fontSize: 10.5, fontWeight: 700, color: "#57534e", textAlign: "left" },
  companyCityEn: { fontSize: 9, fontWeight: 500, color: "#78716c", textAlign: "left" },

  titleWrap: { alignItems: "center", marginTop: 5, marginBottom: 9 },
  title: {
    fontSize: 16.5,
    fontWeight: 900,
    color: "#111827",
    borderBottomWidth: 1.4,
    borderBottomStyle: "solid",
    borderBottomColor: "#d6b46a",
    paddingBottom: 3,
    textAlign: "center",
  },

  metaGrid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 5,
    marginBottom: 7,
  },
  metaCell: {
    width: "32.25%",
    borderWidth: 0.5,
    borderStyle: "solid",
    borderColor: "#e5e7eb",
    borderRadius: 5,
    backgroundColor: "#fbfbfa",
    padding: 6,
  },
  metaLabel: {
    fontSize: 8.5,
    fontWeight: 700,
    color: "#64748b",
    textAlign: "right",
    marginBottom: 3,
  },
  metaValue: {
    fontSize: 10.5,
    fontWeight: 900,
    color: "#111827",
    textAlign: "right",
    maxLines: 1,
    textOverflow: "ellipsis",
  },

  summaryGrid: {
    flexDirection: "row-reverse",
    gap: 5,
    marginBottom: 6,
  },
  summaryCard: {
    flex: 1,
    paddingVertical: 7,
    paddingHorizontal: 6,
    borderWidth: 0.5,
    borderStyle: "solid",
    borderColor: "#e5e7eb",
    borderRadius: 5,
    alignItems: "center",
  },
  cardTotal: {
    backgroundColor: "#f9fafb",
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "#94a3b8",
  },
  cardPaid: {
    backgroundColor: "#f4fbf6",
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "#22c55e",
  },
  cardRemaining: {
    backgroundColor: "#fff6f6",
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "#ef4444",
  },
  cardDeposit: {
    backgroundColor: "#f4fbf6",
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "#22c55e",
  },
  cardWithdraw: {
    backgroundColor: "#fff6f6",
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "#ef4444",
  },
  cardNet: {
    backgroundColor: "#f9fafb",
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "#94a3b8",
  },
  cardLabel: { fontSize: 8.5, fontWeight: 700, color: "#64748b", textAlign: "center", marginBottom: 3 },
  cardValue: { fontSize: 11, fontWeight: 900, color: "#1e293b", textAlign: "center", maxLines: 1, textOverflow: "ellipsis" },
  valueRed: { color: "#b91c1c", textAlign: "center" },
  valueGreen: { color: "#15803d", textAlign: "center" },

  netRow: { flexDirection: "column", alignItems: "center" },
  netSummaryBox: { flexDirection: "column", alignItems: "center", gap: 6, width: "100%" },
  netGroup: { flexDirection: "column", alignItems: "center", width: "100%" },
  netLabel: { fontSize: 8.5, color: "#475569", fontWeight: 700, marginBottom: 2, textAlign: "center" },
  netLabelMuted: { color: "#64748b", textAlign: "center" },
  netLabelDebt: { color: "#b91c1c", textAlign: "center" },
  netValue: { fontSize: 12, fontWeight: 900, color: "#1e293b", lineHeight: 1.2, textAlign: "center" },
  netValueMuted: { fontSize: 11, color: "#64748b", marginTop: 2, textAlign: "center" },
  netValueDebt: { color: "#b91c1c", textAlign: "center" },

  installmentStrip: {
    flexDirection: "row-reverse",
    justifyContent: "center",
    gap: 16,
    borderWidth: 0.5,
    borderStyle: "dashed",
    borderColor: "#d6b46a",
    borderRadius: 5,
    paddingVertical: 5,
    paddingHorizontal: 6,
    marginBottom: 6,
    backgroundColor: "#fffdf8",
  },
  installmentText: { fontSize: 9.5, fontWeight: 800, color: "#334155", textAlign: "center", maxLines: 1, textOverflow: "ellipsis" },

  tableHeader: {
    flexDirection: "row-reverse",
    backgroundColor: "#111827",
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderWidth: 0.5,
    borderStyle: "solid",
    borderColor: "#111827",
    paddingVertical: 6,
    paddingHorizontal: 0,
    marginBottom: 0,
  },
  th: { fontSize: 9.5, fontWeight: 800, color: "#ffffff", textAlign: "center", paddingHorizontal: 5 },
  tableRow: {
    flexDirection: "row-reverse",
    borderBottomWidth: 0.5,
    borderBottomStyle: "solid",
    borderBottomColor: "#e5e7eb",
    borderLeftWidth: 0.5,
    borderLeftStyle: "solid",
    borderLeftColor: "#e5e7eb",
    borderRightWidth: 0.5,
    borderRightStyle: "solid",
    borderRightColor: "#e5e7eb",
    paddingVertical: 5,
    paddingHorizontal: 0,
    minHeight: 23,
    alignItems: "center",
  },
  tableRowAlt: { backgroundColor: "#f9fafb" },
  rowDebit: { backgroundColor: "#fffafa" },
  rowCredit: { backgroundColor: "#f8fdf9" },
  td: { fontSize: 9.5, color: "#1c1917", textAlign: "center", lineHeight: 1.15, paddingHorizontal: 5 },
  amountDebit: { color: "#b91c1c", fontWeight: 800, textAlign: "center" },
  amountCredit: { color: "#15803d", fontWeight: 800, textAlign: "center" },

  colSeq: {
    width: "7%",
    textAlign: "center",
    borderLeftWidth: 0.5,
    borderLeftStyle: "solid",
    borderLeftColor: "#cbd5e1",
  },
  colDate: {
    width: "15%",
    textAlign: "center",
    borderLeftWidth: 0.5,
    borderLeftStyle: "solid",
    borderLeftColor: "#cbd5e1",
  },
  colType: {
    width: "17%",
    textAlign: "center",
    borderLeftWidth: 0.5,
    borderLeftStyle: "solid",
    borderLeftColor: "#cbd5e1",
  },
  colAmount: {
    width: "22%",
    textAlign: "center",
    borderLeftWidth: 0.5,
    borderLeftStyle: "solid",
    borderLeftColor: "#cbd5e1",
  },
  colNotes: { width: "39%", textAlign: "right", paddingRight: 8 },
  singleLineText: { maxLines: 1, textOverflow: "ellipsis" },

  emptyState: {
    borderWidth: 0.5,
    borderStyle: "dashed",
    borderColor: "#d6d3d1",
    borderRadius: 5,
    padding: 20,
    alignItems: "center",
    marginTop: 8,
  },
  emptyText: { color: "#78716c", fontWeight: 700, fontSize: 11, textAlign: "center" },

  footer: {
    position: "absolute",
    bottom: 18,
    left: 26,
    right: 26,
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "#cbd5e1",
    paddingTop: 5,
  },
  footerLeft: { flexDirection: "row-reverse", alignItems: "center", gap: 4, flex: 1, paddingRight: 4 },
  footerRight: { fontSize: 8.5, color: "#4b5563", textAlign: "left" },
  footerRole: { fontSize: 9, fontWeight: 700, color: "#4b5563", textAlign: "right" },
  footerName: { fontSize: 9.2, fontWeight: 800, color: "#111827", textAlign: "right" },
  footerPhone: { fontSize: 8.7, fontWeight: 700, color: "#4b5563", textAlign: "left" },
  footerDivider: { color: "#d1d5db", fontSize: 9, textAlign: "center" },
});
